name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  jaspr: 0.12.0
  jaspr_blog:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner:
  jaspr_builder: ^0.12.0

jaspr:
  mode: static