name: jaspr_blog
description: A Hugo-esque static site generator for blogs.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dependencies:
  jaspr: ^0.12.0
  jaspr_cli: 
  jaspr_router: ^0.4.0
  markdown:
  image:
  uuid:
  args:
  path:
  yaml: ^3.1.2
  intl: ^0.19.0
  xml: ^6.5.0
      
dev_dependencies:
  build_runner: ^2.4.0
  jaspr_builder: ^0.12.0
  # jaspr_web_compilers: ^4.0.9
  lints: ^2.1.0
  analyzer:
